#!/usr/bin/env node
/**
 * Generates the Angular 20+ package from data/icon-data.json.
 *
 * Usage: node packages/reicon-angular/scripts/build.cjs
 */

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const PACKAGE_ROOT = path.join(__dirname, '..');
const ROOT = path.join(PACKAGE_ROOT, '..', '..');
const DATA_PATH = path.join(ROOT, 'data', 'icon-data.json');
const TAGS_PATH = path.join(ROOT, 'data', 'icon-tags.json');
const SRC = path.join(PACKAGE_ROOT, 'src');
const ICONS_SRC = path.join(SRC, 'icons');
const DIST = path.join(PACKAGE_ROOT, 'dist');

const WEIGHT_KEYS = { Filled: 'F', Outline: 'O' };
const RESERVED_EXPORT_NAMES = new Set([
  'icon',
  'iconprops',
  'iconweight',
  'iconcomponent',
  'reiconicon',
]);

function toPascalCase(value) {
  return value
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function stripSvgWrapper(code) {
  if (!code) return '';
  return code.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
}

function rewriteColors(svg) {
  return svg.replace(/fill="white"/g, 'fill="currentColor"');
}

function collectIcons() {
  const data = JSON.parse(fs.readFileSync(DATA_PATH, 'utf8'));
  const tags = fs.existsSync(TAGS_PATH) ? JSON.parse(fs.readFileSync(TAGS_PATH, 'utf8')) : {};
  const icons = [];
  const usedNames = new Set(RESERVED_EXPORT_NAMES);

  for (const [category, categoryData] of Object.entries(data.categories || {})) {
    for (const [kebab, icon] of Object.entries(categoryData.icons || {})) {
      let pascal = toPascalCase(kebab);
      if (usedNames.has(pascal.toLowerCase())) {
        pascal += toPascalCase(category);
      }
      usedNames.add(pascal.toLowerCase());

      const weights = {};
      for (const [weightName, weightData] of Object.entries(icon.weights || {})) {
        const key = WEIGHT_KEYS[weightName];
        if (key && weightData.code) {
          weights[key] = rewriteColors(stripSvgWrapper(weightData.code));
        }
      }

      if (Object.keys(weights).length > 0) {
        icons.push({
          kebab,
          pascal,
          category,
          weights,
          tags: tags[kebab] || icon.description || [],
        });
      }
    }
  }

  icons.sort((a, b) => a.pascal.localeCompare(b.pascal));
  return icons;
}

function writeIconComponent(icon) {
  const dataEntries = Object.entries(icon.weights)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)}`)
    .join(',\n');

  const template = `<svg xmlns="http://www.w3.org/2000/svg" [attr.width]="size" [attr.height]="size" viewBox="0 0 24 24" fill="none" [class]="svgClass" [style.color]="color" [style]="svgStyle" [attr.id]="id" [attr.title]="title" [attr.role]="role" [attr.aria-label]="ariaLabel" [attr.aria-hidden]="ariaHidden" [innerHTML]="svgMarkup"></svg>`;

  const source = `import { ChangeDetectionStrategy, Component } from '@angular/core';
import { ReiconIcon } from '../reicon-icon';

const ICON_DATA = {
${dataEntries}
} as const;

@Component({
  selector: 'ri-${icon.kebab}',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: ${JSON.stringify(template)},
})
export class ${icon.pascal}Component extends ReiconIcon {
  protected override readonly iconData = ICON_DATA;
}

export default ${icon.pascal}Component;
`;

  fs.writeFileSync(path.join(ICONS_SRC, `${icon.pascal}.component.ts`), source);
}

function writePublicApi(icons) {
  const exports = icons
    .map((icon) => `export { ${icon.pascal}Component, ${icon.pascal}Component as ${icon.pascal} } from './icons/${icon.pascal}.component';`)
    .join('\n');

  fs.writeFileSync(
    path.join(SRC, 'public-api.ts'),
    `// Auto-generated by scripts/build.cjs – do not edit.\nexport { ReiconIcon, IconProps, IconWeight } from './reicon-icon';\n\n${exports}\n`,
  );
}

function writeReadme(iconCount) {
  const readme = `<div align="center">

<br/>

<img src="https://reicon.dev/readme-assets/banner.webp" alt="Reicon Angular" width="200" />

<br/>

### Official Reicon package for Angular 20+ – open-source icon library for designers & developers

[![npm](https://img.shields.io/npm/v/reicon-angular?style=flat-square&label=reicon-angular&color=DD0031)](https://www.npmjs.com/package/reicon-angular)
[![Docs](https://img.shields.io/badge/Docs-reicon.dev-9B8AFB?style=flat-square)](https://reicon.dev/docs/angular)
[![License](https://img.shields.io/badge/License-MIT-9B8AFB?style=flat-square)](https://github.com/dqev/reicon/blob/main/LICENSE)

</div>

<br/>

**reicon-angular** provides ${iconCount}+ standalone Angular components generated from the Reicon icon dataset. It targets Angular 20 and newer, is fully TypeScript-ready, and ships with Outline and Filled weights.

## Installation

\`\`\`bash
npm install reicon-angular
# or
pnpm add reicon-angular
# or
yarn add reicon-angular
\`\`\`

## Quick start

Import the standalone components you use and add them to the component's \`imports\` array:

\`\`\`ts
import { Component } from '@angular/core';
import { BellComponent, HomeComponent, ShieldCheckComponent } from 'reicon-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [HomeComponent, ShieldCheckComponent, BellComponent],
  template: \`\
    <nav>
      <ri-home [size]="24"></ri-home>
      <ri-shield-check size="24" color="#9B8AFB"></ri-shield-check>
      <ri-bell size="24" weight="Filled"></ri-bell>
    </nav>
  \`\,
})
export class AppComponent {}
\`\`\`

The component selectors follow the original kebab-case icon names: \`home\` becomes \`ri-home\`, while the exported class is \`HomeComponent\`.

## Inputs

| Input | Type | Default | Description |
| ---- | ---- | ------- | ----------- |
| \`size\` | \`number \\| string\` | \`24\` | Icon width and height. |
| \`color\` | \`string\` | inherited | Primary icon color. |
| \`weight\` | \`'Outline' \\| 'Filled'\` | \`'Outline'\` | Visual weight style. |
| \`strokeWidth\` | \`number \\| string\` | source default | Override the source stroke width where supported. |
| \`class\` | \`string\` | – | CSS class applied to the SVG element. |
| \`style\` | \`string \\| Record<string, string \\| number>\` | – | Inline styles applied to the SVG element. |

Common \`id\`, \`title\`, \`role\`, \`aria-label\`, and \`aria-hidden\` inputs are forwarded to the SVG element.

## Tree-shaking

Each icon is an independent standalone component. Import only the components used by your application so Angular's build pipeline can remove unused icons.

## Requirements

- Angular 20 or newer
- TypeScript 5.8 or newer
- No runtime dependencies beyond Angular

## Related packages

See the complete Reicon ecosystem at [reicon.dev/packages](https://reicon.dev/packages).

## License

MIT © [Dev Chauhan](https://devchauhan.in)
`;

  fs.writeFileSync(path.join(PACKAGE_ROOT, 'README.md'), readme);
}

function build() {
  const icons = collectIcons();
  console.log(`Found ${icons.length} icons`);

  fs.rmSync(ICONS_SRC, { recursive: true, force: true });
  fs.mkdirSync(ICONS_SRC, { recursive: true });
  for (const icon of icons) writeIconComponent(icon);
  fs.writeFileSync(path.join(ICONS_SRC, '.gitkeep'), '# Keep directory in Git\n');
  writePublicApi(icons);
  writeReadme(icons.length);

  fs.rmSync(DIST, { recursive: true, force: true });
  const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx';
  const result = spawnSync(npx, ['--no-install', 'ng-packagr', '-p', path.join(PACKAGE_ROOT, 'ng-package.json')], {
    cwd: ROOT,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });

  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status ?? 1);

  const packageReadme = path.join(PACKAGE_ROOT, 'README.md');
  if (fs.existsSync(packageReadme)) {
    fs.copyFileSync(packageReadme, path.join(DIST, 'README.md'));
  }

  const nameMap = Object.fromEntries(icons.map((icon) => [icon.kebab, `${icon.pascal}Component`]));
  fs.writeFileSync(path.join(DIST, 'icon-names.json'), JSON.stringify(nameMap, null, 2) + '\n');
  console.log(`Built ${icons.length} Angular standalone components in ${DIST}`);
}

build();
